# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
#       - uses: montudor/action-zip@v0.1.0
#         with:
#           args: zip -qq -r ./theme.zip ./theme

#       - uses: actions/upload-artifact@v2
#         with:
#           name: temptest.zip
#           path: ./temptest.zip

      - uses: zdurham/s3-upload-github-action@master
        with:
         args: --acl public-read
        env:
          FILE: ./temptest.zip
          AWS_REGION: 'us-east-1'
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

