# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./theme.zip ./theme

      - uses: andstor/file-existence-action@v1
        with:
          files: "theme.zip" 

      - uses: actions/upload-artifact@v2
        with:
          name: ./theme.zip

