# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
#       - uses: montudor/action-zip@v0.1.0
#         with:
#           args: zip -qq -r ./theme.zip ./theme

#       - uses: actions/upload-artifact@v2
#         with:
#           name: temptest.zip
#           path: ./temptest.zip

#       - uses: zdurham/s3-upload-github-action@master
#         with:
#          args: --acl public-read
#         env:
#           FILE: ./temptest.zip
#           AWS_REGION: 'us-east-1'
#           S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#       - run: echo -n -e "{\"theme\":{\"name\":\"GitHubActionsTest - $(date +"%D %T %Z")\",\"src\":\"$FILE_PATH\"}}" > body.json
#         env:
#           FILE_PATH: https://shopify-cypress-demo.s3.amazonaws.com/temptest.zip  
#       - run: echo $(cat body.json)

      - uses: Satak/webrequest-action@v1.2.3
        with:
          url: https://${SHOPIFY_API_KEY}:${SHOPIFY_API_PASSWORD}@${SHOPIFY_URL}/admin/api/2019-04/themes.json
          method: POST
          payload: '{"theme":{"name":"GitHubActionsTest - $(date +"%D %T %Z")","src":"$FILE_PATH"}}'
        env:
          FILE_PATH: https://shopify-cypress-demo.s3.amazonaws.com/temptest.zip   
      - run: |
          $output = '${{ steps.webhook.outputs }}' | ConvertFrom-Json
          echo $output
